name: quarc
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - cairo=1.18.0
  - chardet=5.2.0
  - comm=0.2.2
  - contourpy=1.3.2
  - cycler=0.12.1
  - debugpy=1.8.15
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - faiss=1.7.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.0
  - freetype=2.13.3
  - freetype-py=2.3.0
  - greenlet=3.2.3
  - icu=73.2
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-python=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libfaiss=1.7.4
  - libfaiss-avx2=1.7.4
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsodium=1.0.20
  - libsqlite=3.50.3
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openssl=3.5.1
  - pandas=2.3.1
  - parso=0.8.4
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.1.1
  - pixman=0.46.2
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycairo=1.27.0
  - pygments=2.19.2
  - pyparsing=3.2.3
  - python=3.11.2
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - pyzmq=27.0.0
  - qhull=2020.2
  - rdkit=2023.09.5
  - readline=8.2
  - reportlab=4.4.1
  - rlpycairo=0.2.0
  - setuptools=80.9.0
  - six=1.17.0
  - sqlalchemy=2.0.41
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aimsim-core==2.2.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - anyio==4.9.0
      - arrow==1.3.0
      - astartes==1.3.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - blessed==1.21.0
      - boto3==1.39.9
      - botocore==1.39.9
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - chemprop==2.0.0
      - click==8.2.1
      - cloudpickle==3.1.1
      - configargparse==1.7.1
      - croniter==1.3.15
      - dateutils==0.6.12
      - deepdiff==7.0.1
      - descriptastorus==2.8.0
      - dill==0.4.0
      - docstring-parser==0.16
      - dotenv==0.9.9
      - editor==1.6.6
      - fastapi==0.88.0
      - filelock==3.18.0
      - frozenlist==1.7.0
      - fsspec==2023.12.2
      - h11==0.16.0
      - idna==3.10
      - inquirer==3.4.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.1
      - lightning==2.2.0
      - lightning-cloud==0.5.70
      - lightning-utilities==0.14.3
      - loguru==0.7.3
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mhfp==1.9.6
      - mordredcommunity==2.0.6
      - mpmath==1.3.0
      - multidict==6.6.3
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - narwhals==1.47.1
      - networkx==3.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - ordered-set==4.1.0
      - packaging==24.2
      - padelpy==0.1.16
      - pandas-flavor==0.7.0
      - plotly==6.2.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==6.1.1
      - pydantic==1.10.22
      - pyjwt==2.10.1
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.0
      - pyyaml==6.0.2
      - quarc==0.0.1
      - readchar==4.2.1
      - requests==2.32.4
      - rich==14.0.0
      - runs==1.2.2
      - s3transfer==0.13.1
      - scikit-learn==1.7.1
      - scipy==1.16.0
      - seaborn==0.13.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - starlette==0.22.0
      - starsessions==1.3.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - torch==2.1.0
      - torcheval==0.0.7
      - torchmetrics==1.7.4
      - tqdm==4.67.1
      - triton==2.1.0
      - typed-argument-parser==1.10.1
      - types-python-dateutil==2.9.0.20250708
      - typing-inspect==0.9.0
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - websocket-client==1.8.0
      - websockets==11.0.3
      - xarray==2025.7.1
      - xmod==1.8.1
      - yarl==1.20.1
